#This template uses jdk8 for veryfying and deplyoing images
image: maven:3.3.9-jdk-8

# Stages
stages: 
    - build
    - test
    - package

# Build job
build_compiler:
    stage: build
    script:
        - cd compiler
        - mvn clean compile

# Test job
test_compiler:
    stage: test
    script:
        - cd compiler
        - mvn test


# Package job
package:
    stage: package
    script: mvn package
    variables:
        MAVEN_OPTS: "-DskipTests=true"


