#This template uses jdk8 for veryfying and deplyoing images
image: maven:3.3.9-jdk-8

#get back to root before and after script 
before_script:
    - cd $CI_PROJECT_DIR

after_script:
    - cd $CI_PROJECT_DIR

# Stages
stages: 
    - build
    - test
    - package
    - publish
    - deploy

# Build job service-registry
build_service_registry:
    stage: build
    script:
        - cd service-registry
        - mvn clean compile

# Build job compiler
build_compiler:
    stage: build
    script:
        - cd compiler
        - mvn clean compile

# Build job project
build_project:
    stage: build
    script:
        - cd project
        - mvn clean compile

# Build job ui
build_ui:
    stage: build
    script:
        - cd UI
        - mvn clean compile

# Build job api-gateway
build_ui:
    stage: build
    script:
        - cd api-gateway
        - mvn clean compile

# Build UI/UI (Angular)
build_ui_angular:

    stage: build
    image: trion/ng-cli
    before_script:
        - cd UI/UI
        - npm ci
    script:
        - ng build


# Test job compiler
test_compiler:
    stage: test
    script:
        - cd compiler
        - mvn test

project-service:test:
    stage: test
    script:
        - cd project
        - mvn test
    services:
        - postgres:9.6
    variables:
        url: jdbc:postgresql://db:5432/my_db?user=admin&password=test
        POSTGRES_DB: my_db
        POSTGRES_PASSWORD: test
        POSTGRES_USER: admin
    only:
        changes:
            - project/**/*

# Package jobs
package_compiler:
    stage: package
    script:
        - cd compiler 
        - mvn package
    artifacts:
        paths:
            - compiler/target/*.jar
    variables:
        MAVEN_OPTS: "-DskipTests=true"

package_project:
    stage: package
    script:
        - cd project 
        - mvn package
    artifacts:
        paths:
            - project/target/*.jar
    variables:
        MAVEN_OPTS: "-DskipTests=true"

package_ui:
    stage: package
    script:
        - cd UI 
        - mvn package
    artifacts:
        paths:
            - ui/target/*.jar
    variables:
        MAVEN_OPTS: "-DskipTests=true"

package_api-gateway:
    stage: package
    script:
        - cd api-gateway 
        - mvn package
    artifacts:
        paths:
            - api-gateway/target/*.jar
    variables:
        MAVEN_OPTS: "-DskipTests=true"

package_service-registry:
    stage: package
    script:
        - cd service-registry
        - mvn package
    artifacts:
        paths:
            - service-registry/target/*.jar
    variables:
        MAVEN_OPTS: "-DskipTests=true"

# publish jobs
service-registry:publish:
    stage: publish
    image: docker:stable
    services:
        - docker:18-dind
    script:
        - cd service-registry/
        - docker login --username $CI_REGSITRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull $IMAGE_NAME:latest || true
        - docker build --tag $IMAGE_NAME:latest .
        - docker push $IMAGE_NAME:latest
    variables:
        DOCKER_DRIVER: overlay2
        DOCKER_HOST: tcp://docker:2375
        IMAGE_NAME: $CI_REGISTRY_IMAGE/discovery-service
    only:
        changes:
            - service-registry/**/*

api-gateway:publish:
    stage: publish
    image: docker:stable
    services:
        - docker:18-dind
    script:
        - cd api-gateway/
        - docker login --username $CI_REGSITRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull $IMAGE_NAME:latest || true
        - docker build --tag $IMAGE_NAME:latest .
        - docker push $IMAGE_NAME:latest
    variables:
        DOCKER_DRIVER: overlay2
        DOCKER_HOST: tcp://docker:2375
        IMAGE_NAME: $CI_REGISTRY_IMAGE/api-gateway-service
    only:
        changes:
            - api-gateway/**/*

project-service:publish:
    stage: publish
    image: docker:stable
    services:
        - docker:18-dind
    script:
        - cd project/
        - docker login --username $CI_REGSITRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull $IMAGE_NAME:latest || true
        - docker build --tag $IMAGE_NAME:latest .
        - docker push $IMAGE_NAME:latest
    variables:
        DOCKER_DRIVER: overlay2
        DOCKER_HOST: tcp://docker:2375
        IMAGE_NAME: $CI_REGISTRY_IMAGE/project-service
    only:
        changes:
            - project/**/*

ui-service:publish:
    stage: publish
    image: docker:stable
    services:
        - docker:18-dind
    script:
        - cd ui/
        - docker login --username $CI_REGSITRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull $IMAGE_NAME:latest || true
        - docker build --tag $IMAGE_NAME:latest .
        - docker push $IMAGE_NAME:latest
    variables:
        DOCKER_DRIVER: overlay2
        DOCKER_HOST: tcp://docker:2375
        IMAGE_NAME: $CI_REGISTRY_IMAGE/ui-service
    only:
        changes:
            - ui/**/*

compiler-service:publish:
    stage: publish
    image: docker:stable
    services:
        - docker:18-dind
    script:
        - cd compiler/
        - docker login --username $CI_REGSITRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY
        - docker pull $IMAGE_NAME:latest || true
        - docker build --tag $IMAGE_NAME:latest .
        - docker push $IMAGE_NAME:latest
    variables:
        DOCKER_DRIVER: overlay2
        DOCKER_HOST: tcp://docker:2375
        IMAGE_NAME: $CI_REGISTRY_IMAGE/compiler-service
    only:
        changes:
            - compiler/**/*


# deploy job
deploy:gcp:
    stage: deploy
    image: ubuntu:18.04
    script: 
        #Install ssh agent
        - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-cleint -y )'
        - eval $(ssh-agent -s)
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        
        - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

        - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
        - scp -r docker-compose.prod.yml $SSH_HOST:~/
        - ssh $SSH_HOST "sudo docker login --username $CI_REGSITRY_USER --password $CI_REGISTRY_PASSWORD $CI_REGISTRY"
        - ssh $SSH_HOST "sudo docker-compose -f docker-compose.prod.yml pull && sudo docker-compose -f docker-compose.prod.yml up"  --force-recreate
    
    variables:
        SSH_HOST: malteradmann@34.69.193.177
    only:
        refs:
            - master    