#This template uses jdk8 for veryfying and deplyoing images
image: maven:3.3.9-jdk-8

# Stages
stages: 
    - build
    - test
    - package

# Build job compiler
build_compiler:
    stage: build
    script:
        - cd compiler
        - mvn clean compile

# Build job project
build_project:
    stage: build
    script:
        - cd project
        - mvn clean compile

# Build job ui
build_ui:
    stage: build
    script:
        - cd UI
        - mvn clean compile

# Build UI/UI (Angular)
build_ui_angular:

    stage: build
    image: trion/ng-cli
    before_script:
        - cd UI/UI
        - npm ci
    script:
        - ng build

# Build job api-gateway
build_ui:
    stage: build
    script:
        - cd api-gateway
        - mvn clean compile

# Build job service-registry
build_ui:
    stage: build
    script:
        - cd service-registry
        - mvn clean compile



# Test job compiler
test_compiler:
    stage: test
    script:
        - cd compiler
        - mvn test


# Package jobs
package_compiler:
    stage: package
    script:
        - cd compiler 
        - mvn package
    variables:
        MAVEN_OPTS: "-DskipTests=true"

package_project:
    stage: package
    script:
        - cd project 
        - mvn package
    variables:
        MAVEN_OPTS: "-DskipTests=true"

package_ui:
    stage: package
    script:
        - cd UI 
        - mvn package
    variables:
        MAVEN_OPTS: "-DskipTests=true"

package_api-gateway:
    stage: package
    script:
        - cd api-gateway 
        - mvn package
    variables:
        MAVEN_OPTS: "-DskipTests=true"

package_service-registry:
    stage: package
    script:
        - cd service-registry
        - mvn package
    variables:
        MAVEN_OPTS: "-DskipTests=true"


