version: "3.7"
services:
  discovery-service:
    build:
      dockerfile: Dockerfile
      context: ./service-registry
    image: discovery-service:latest
    restart: on-failure
    ports:
      - 8761:8761
  api-gateway-service:
    build:
      dockerfile: Dockerfile
      context: ./api-gateway
    image: api-gateway-service:latest
    restart: on-failure
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka
    ports:
    - 80:8080

  compiler-service:
    build:
      dockerfile: Dockerfile
      context: ./compiler
    image: compiler-service:latest
    restart: on-failure
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka
    ports:
    -  9000-9004:8082

  project-service:
    build:
      dockerfile: Dockerfile
      context: ./project
    image: project-service:latest
    restart: on-failure
    depends_on:
      - db
    environment:
      - url=jdbc:postgresql://db:5432/my_db?user=admin&password=test
      - EUREKA_SERVER=http://discovery-service:8761/eureka
    ports:
    - 9005-9009:8081

  db:
    image: postgres:9.6
    environment:
      - POSTGRES_DB=my_db
      - POSTGRES_PASSWORD=test
      - POSTGRES_USER=admin
  ui-service:
    build:
      dockerfile: Dockerfile
      context: ./UI
    image: ui-service:latest
    restart: on-failure
    environment:
      - EUREKA_SERVER=http://discovery-service:8761/eureka
    ports:
    - 9010-9014:8084



