spring:
  application:
    name: api-gateway-service
server:
  port: ${PORT:8080}
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
zuul.host.socket-timeout-millis: 20000
zuul.host.connect-timeout-millis: 20000
ribbon.ConnectTimeout: 10000
ribbon.ReadTimeout: 10000

security:
  oauth2:
    client:
      clientId: e8137be3be8cb7ab591610fa986e8a24ff2b0ba32757ea1c473d531ca83afd7c
      clientSecret: 25dc36399e67a8e636ae369aeab71b14c0d918d962b7cee041a0f79364f68418
      accessTokenUri: https://gitlab.lrz.de/oauth/token
      userAuthorizationUri: https://gitlab.lrz.de/oauth/authorize
      scope:
        - read_user
        - api
    resource:
      userInfoUri: https://gitlab.lrz.de/api/v4/user

zuul:
  # All services are added into Zuul routes automatically as default.
  # You can disable it with the ignored-services property set to *.
  ignored-services: "*"
  routes:
    project-service:
      path: "/api/projects/**"
      service-id: project-service
      strip-prefix: false
      sensitiveHeaders: Cookie,Set-Cookie # Authentication
    ui-service:
      path: "/ui/**"
      service-id: ui-service
      strip-prefix: false
    compiler-service:
      path: "/compile/**"
      service-id: compiler-service
      strip-prefix: false
proxy:
  auth:
    routes:
      project-service: oauth2



