spring:
  application:
    name: ui-service
server:
  port: ${PORT:8080}
  servlet:
    context-path: /ui
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}
