spring:
    application:
        name: project-service
    datasource:
        name: my_db
        url: "${url:jdbc:postgresql://localhost:5432/my_db}"
        username: admin
        password: test
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
                jdbc:
                    lob:
                        non_contextual_creation: true

    jackson:
        serialization:
            FAIL_ON_EMPTY_BEANS: false
database:
    port: 5432
server:
    port: ${PORT:8081}
eureka:
    client:
        serviceUrl:
            defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka}

security:
    oauth2:
        client:
            clientId: e8137be3be8cb7ab591610fa986e8a24ff2b0ba32757ea1c473d531ca83afd7c
            clientSecret: 25dc36399e67a8e636ae369aeab71b14c0d918d962b7cee041a0f79364f68418
            accessTokenUri: https://gitlab.lrz.de/oauth/token
            userAuthorizationUri: https://gitlab.lrz.de/oauth/authorize
            scope:
                - read_user
                - api
        resource:
            userInfoUri: https://gitlab.lrz.de/api/v4/user


