server:
  port: 8084
security:
  oauth2:
    client:
      clientId: e8137be3be8cb7ab591610fa986e8a24ff2b0ba32757ea1c473d531ca83afd7c
      clientSecret: 25dc36399e67a8e636ae369aeab71b14c0d918d962b7cee041a0f79364f68418
      accessTokenUri: https://gitlab.lrz.de/oauth/token
      userAuthorizationUri: https://gitlab.lrz.de/oauth/authorize
      scope:
        - read_user
        - api
    resource:
      userInfoUri: https://gitlab.lrz.de/api/v4/user
